spring.application.name=configservers
#reading from a file system inside a class path
#spring.profile.active=native
#Where the config server has to search the file and load configurations
#spring.cloud.config.server.native.search-locations=classpath:/config
# read the config from file system
#spring.cloud.config.server.native.search-locations=file://C://config

### read from github ###
spring.profile.active=git
spring.cloud.config.server.git.url=https://github.com/example/configs.git
spring.cloud.config.server.git.clone-on-start=true
# main = branch use to read config value
spring.cloud.config.server.git.default-label=main

server.port=8071